export const TEAMS = [
  "U6",
  "U8 A",
  "U8 B",
  "U10 GARCON LOUPS",
  "U10 GARCONS LIONS",
  "U10 GARCON TIGRES",
  "U12 A garçons",
  "U12 B garçons",
  "U12 filles",
  "U14B garçons",
  "U14 AWBB garçons",
  "U14 filles",
  "U16 B filles",
  "U16 AWBB filles",
  "U16 Hommes",
  "U16 dames",
  "U18 hommes",
  "U21 hommes",
  "P4 hommes",
  "P3 hommes",
  "P2 hommes",
  "Vétérans"
];
