export const TEAMS = [
  "U6",
  "U8 A",
  "U8 B",
  "U10 LOUPS",
  "U10 LIONS",
  "U10 TIGRES",
  "U12 Garçons A",
  "U12 Garçons B",
  "U12 Filles",
  "U14 AWBB Garçons",
  "U 14 B Garçons",
  "U14 Filles",
  "U16 Hommes",
  "U16 AWBB Dames",
  "U16 B Dames",
  "U18 Hommes",
  "U21 Hommes",
  "P4 Hommes",
  "P3 Hommes",
  "P2 Hommes",
  "Vétérans"
];
